In [48]:
import numpy as np               # used for multidimensional arrays
import pandas as pd              # used for import the dataset

In [49]:
adult = pd.read_csv("adult_num.csv")

Define the predittor and target attributes


In [76]:
value_counts = adult['age'].value_counts()
# Get the ages (classes) that appear only once
to_remove = value_counts[value_counts == 1].index
adult_filtered = adult[~adult['age'].isin(to_remove)]
print(f"Original number of rows: {len(adult)}")
print(f"Number of rows after removing rare classes: {len(adult_filtered)}")
X = adult_filtered.drop("income", axis=1)
y = adult_filtered['income']


# ✅ Step 3: Now, split the data using stratification. It will work.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0, stratify=y)

Original number of rows: 32561
Number of rows after removing rare classes: 32559


In [74]:
###################
###   Bagging   ###
###################

#import bagging
from sklearn.ensemble import BaggingClassifier

#import classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

#initialise classifier
#default is Decision tree
#BC = BaggingClassifier(estimator=SVC(), n_estimators=10, random_state=0)
#BC = BaggingClassifier(estimator=KNeighborsClassifier(n_neighbors=5), n_estimators=10, random_state=0)
#BC = BaggingClassifier(estimator=GaussianNB(), n_estimators=10, random_state=0)
BC = BaggingClassifier(n_estimators=10, random_state=0)   # 10 just used for easiness, you can try other number. 

#fit the classifier to the data
BC.fit(X_train, y_train)

#predict the values for the test set
y_pred = BC.predict(X_test)

#performance metrics
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score
from sklearn.model_selection import cross_val_score

print(confusion_matrix(y_test, y_pred), '\n')

print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
# print("AUC:", roc_auc_score(y_test, y_pred))  # if data is binary , use AUC to evaluate 


[[67 24  3 ...  0  0  0]
 [39 32 15 ...  0  0  0]
 [ 6 18 38 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  1 ...  0  0  0]] 

              precision    recall  f1-score   support

          17       0.47      0.68      0.56        99
          18       0.22      0.23      0.22       138
          19       0.16      0.21      0.18       178
          20       0.13      0.17      0.15       188
          21       0.07      0.08      0.08       180
          22       0.07      0.09      0.08       191
          23       0.06      0.07      0.07       219
          24       0.05      0.06      0.05       200
          25       0.06      0.08      0.07       210
          26       0.06      0.08      0.07       196
          27       0.04      0.05      0.05       209
          28       0.04      0.05      0.05       217
          29       0.04      0.04      0.04       203
          30       0.03      0.03      0.03       215
          31       0.03      0.

c:\Users\frank\.conda\envs\py311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\frank\.conda\envs\py311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\frank\.conda\envs\py311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [ ]:
# But if the data you are going to prediect is not binary, you should use ( multi_class= type) here 
NB = GaussianNB()
NB.fit(X_train, y_train)
y_pred = NB.predict(X_test)
y_pred_proba = NB.predict_proba(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, zero_division=0))
print('Accuracy:', accuracy_score(y_test, y_pred))

# This line will now work correctly
print('AUC: ', roc_auc_score(y_test, y_pred_proba, multi_class='ovr'))

[[78  1  0 ...  1  0  0]
 [57  4  1 ...  5  6  0]
 [ 9  2  0 ...  9 12  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 1  0  0 ...  0  2  0]]
              precision    recall  f1-score   support

          17       0.39      0.79      0.52        99
          18       0.33      0.03      0.05       138
          19       0.00      0.00      0.00       178
          20       0.10      0.09      0.09       188
          21       0.00      0.00      0.00       180
          22       0.05      0.01      0.01       191
          23       0.05      0.08      0.06       219
          24       0.00      0.00      0.00       200
          25       0.03      0.00      0.01       210
          26       0.50      0.01      0.02       196
          27       0.00      0.00      0.00       209
          28       0.00      0.00      0.00       217
          29       0.00      0.00      0.00       203
          30       0.00      0.00      0.00       215
          31       0.00      0.00

In [77]:
######################################
###         Random Forest          ###
######################################

from sklearn.ensemble import RandomForestClassifier

#initialise classifier
#RF = RandomForestClassifier(max_depth=10, random_state=0)
RF = RandomForestClassifier(random_state=0)

#fit the classifier to the data
RF.fit(X_train, y_train)

#predict the values for the test set
y_pred = RF.predict(X_test)

#performance metrics
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score

print(confusion_matrix(y_test, y_pred), '\n')

print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("AUC:", roc_auc_score(y_test, y_pred))

[[5780  400]
 [ 745 1215]] 

              precision    recall  f1-score   support

           0       0.89      0.94      0.91      6180
           1       0.75      0.62      0.68      1960

    accuracy                           0.86      8140
   macro avg       0.82      0.78      0.79      8140
weighted avg       0.85      0.86      0.85      8140

Accuracy: 0.8593366093366094
AUC: 0.7775865200449112


In [28]:
###################
###   Boosting   ###
###################

#import adaboost
from sklearn.ensemble import AdaBoostClassifier

#import classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

#initialise classifier
#default is Decision Tree
AB = AdaBoostClassifier(n_estimators=100, random_state=0)
#AB = AdaBoostClassifier(estimator=GaussianNB(), n_estimators=100, random_state=0)
#AB = AdaBoostClassifier(estimator=SVC(probability=True, kernel = 'linear'), n_estimators=100, random_state=0)

#fit the classifier to the data
AB.fit(X_train, y_train)

#predict the values for the test set
y_pred = AB.predict(X_test)

#performance metrics
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score

print(confusion_matrix(y_test, y_pred), '\n')

print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("AUC:", roc_auc_score(y_test, y_pred))

[[2701    0]
 [   0 5440]] 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2701
           1       1.00      1.00      1.00      5440

    accuracy                           1.00      8141
   macro avg       1.00      1.00      1.00      8141
weighted avg       1.00      1.00      1.00      8141

Accuracy: 1.0
AUC: 1.0


In [8]:
###################
###   Stacking   ###
###################

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import StackingClassifier


# Define base learners
base_learners = [
    ('lr', LogisticRegression(max_iter=10000)),
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('knn', KNeighborsClassifier())
]

# Define meta-learner
meta_learner = LogisticRegression(max_iter=10000)

# Create stacking classifier
stacking_model = StackingClassifier(
    estimators=base_learners,
    final_estimator=meta_learner,
    cv=5
)

# Train stacking model
stacking_model.fit(X_train, y_train)

# Predictions
y_pred = stacking_model.predict(X_test)


#performance metrics
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score

print(confusion_matrix(y_test, y_pred), '\n')

print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("AUC:", roc_auc_score(y_test, y_pred))

c:\Users\frank\.conda\envs\py311\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 10000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=10000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\frank\.conda\envs\py311\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 10000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=10000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preproces

[[5767  392]
 [ 940 1042]] 

              precision    recall  f1-score   support

           0       0.86      0.94      0.90      6159
           1       0.73      0.53      0.61      1982

    accuracy                           0.84      8141
   macro avg       0.79      0.73      0.75      8141
weighted avg       0.83      0.84      0.83      8141

Accuracy: 0.8363837366416902
AUC: 0.7310424441830673


## Exercise (part9) 

Lets remove some attributes to see if the result's accuracy remains or changes. 

For simplicity, lets remove the first elements of the data: